### ISSUE TITLE
有关loss计算的bug

### ISSUE THREAD

**Issue by yanhan19940405** [xhw205/GPLinker_torch#15]
你好，在duie v1数据使用您的代码进行关系抽取任务时，发现loss部分存在报错。
![image](https://user-images.githubusercontent.com/11435099/206403275-a9143084-7bfa-45c2-8144-46fd235915ad.png)
报错是gather计算的index<=dim的问题。
在GPU上直接报如下错误：

![F8UWZ@J06QBY8SRBV0QTONL](https://user-images.githubusercontent.com/11435099/206403856-cb7d15eb-cb72-485d-8ca9-859a1d050545.png)

在出现这个错误前，代码整体平稳运行跑了24000条数据，同时loss下降均匀，无异常，还麻烦作者看看什么问题？

**Comment by yanhan19940405** [comment]
解决了，数据质量问题

**Comment by hanlin1119** [comment]
> 解决了，数据质量问题

可以请教一下duie是哪里有问题么，我在用duie运行也是这种错误，是schema里面关系不完整么
RuntimeError: CUDA error: device-side assert triggered
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115: operator(): block: [0,0,0], thread: [33,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115: operator(): block: [0,0,0], thread: [36,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
